"""rename department

Revision ID: 17be59cd77c9
Revises: 544c062422b8
Create Date: 2024-04-03 00:39:20.329720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17be59cd77c9'
down_revision = '544c062422b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
