"""add Department

Revision ID: 544c062422b8
Revises: 862143fd6384
Create Date: 2024-04-03 00:36:12.459182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544c062422b8'
down_revision = '862143fd6384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
